name: Docker CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t devops-task-manager .

      - name: Run Docker container
        run: docker run -d --name devops-task-manager-container -p 8082:80 devops-task-manager

      - name: Check container
        run: docker ps -a

      - name: Check container logs
        run: docker logs devops-task-manager-container

      - name: Test application
        run: docker exec devops-task-manager-container wget -qO- http://localhost:80

      - name: Stop container
        run: docker stop devops-task-manager-container
